# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5e50a9d58786047b5ad5cde745922c3138e83926cb216503b98363b3365e520a2fdd1dcdb78483a2308b89a01b6d8a6be41d2c121554878fbd17e2fd85cf13

test:
  secret_key_base: dbfdb434ce9d55fda6b839c567dc0fd279113d7ecc5b57a4b0fdd61285cc068634e3af7484325f31f81e29e9c81fd0e10a4239e5006f2459009e70136182137f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
